name: Frontend Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/*"
          target: "/var/www/ats/frontend/dist/"
          overwrite: true
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        script: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
          npm ci
          npm run build

      - name: Restart Frontend application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo nginx -t
            sudo systemctl reload nginx
            echo "Frontend deployment completed successfully"
